spring.application.name=CreditCardApp
spring.data.mongodb.uri=mongodb+srv://CreditCardUsers:CCumydatabase123=@cluster.bhq7tfs.mongodb.net/?appName=Cluster
spring.data.mongodb.database=CreditCardUsers
