version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: creditcard-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: creditcard-server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/creditcarddb

  client:
    build: ./client
    container_name: creditcard-client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo-data: