spring.application.name=CreditCardApp
spring.data.mongodb.uri=mongodb+srv://haranya135_db_user:IhzNkCjsknSYBL8c@creditcard-cluster.goga1ng.mongodb.net/?appName=creditcard-cluster
spring.data.mongodb.database=creditcarddb
